# Generated by Django 5.0.4 on 2024-05-02 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendor_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="vendor_reference",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="acknowledgment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="quality_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="average_response_time",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="vendor",
            name="fulfillment_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="vendor",
            name="on_time_delivery_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="vendor",
            name="quality_rating_avg",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="items",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="contact_details",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="HistoricalPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("on_time_delivery_rate", models.FloatField()),
                ("quality_rating_avg", models.FloatField()),
                ("average_response_time", models.FloatField()),
                ("fulfillment_rate", models.FloatField()),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendor_app.vendor",
                    ),
                ),
            ],
        ),
    ]
